### ISSUE TITLE
Security implications of using Railtrack

### ISSUE THREAD

**Issue by alpharde** [JeevesTakesOver/Railtrack#25]
I am looking for a piece of software that will allow me to build a network of untrusted peers across the city/state/country.
 I came across this repo by asking the same question on tinc's mail list, where I was informed that it was most likely not cut to the job.
Can you answer me if Railtrack implements any sort of security on the regard of handing out IPs, subnets, malicious broadcasts, et cetera?

**Comment by Azulinho** [comment]
Railtrack deploys a L2 tinc network, and then assigns IPs using dhcp.
See: https://github.com/JeevesTakesOver/Railtrack/blob/master/config/config.yaml#L248:L264

Right now it's a single subnet, see:
https://github.com/JeevesTakesOver/Railtrack/blob/master/config/config.yaml#L153:L154

due to the way tinc works by default, any 'trusted' peer in the network is able to access any other peer directly (as long there is connectivity). That means that you are looking to implement rules that block certain traffic, you'd have to apply those across every node logged into the VPN.

You can however change the default tinc behaviour and enable strictsubnets, which would then force all trafic to go through a set of central nodes, in my Railtrack setup these are the core01..03 nodes.
see https://github.com/JeevesTakesOver/Railtrack/blob/master/config/config.yaml#L248:L264

Then you could just implement iptables/ebtables on those 3 nodes to block traffic on the 'core-vpn' interfaces, that would block dodgy packets from travelling through the network.
